---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: pvc
spec:
  trigger:
    schedule: "* * * * *"
  rclone:
    rcloneConfigSection: "aws-s3-bucket"
    rcloneDestPath: "bucket/pvc"
    rcloneConfig: "rclone-secret"
    copyMethod: Snapshot
    accessModes: [ReadWriteOnce]
    capacity: 1Gi
    storageClassName: managed-csi
    volumeSnapshotClassName: csi-azuredisk-vsc
