apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio-role
  namespace: minio
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - minio.min.io
  resources:
  - tenants
  verbs:
  - get
  - list
  - watch
