apiVersion: v1
data:
  config.env: ZXhwb3J0IE1JTklPX1JPT1RfVVNFUj0iMk9VM1lWM0FMV0ROQ1JaMSIKZXhwb3J0IE1JTklPX1JPT1RfUEFTU1dPUkQ9IktIUVFKWkkzVjFaSk5UMklRSUNLSE1ZQjFXU0FEQlcwIgpleHBvcnQgTUlOSU9fU1RPUkFHRV9DTEFTU19TVEFOREFSRD0iRUM6MiIKZXhwb3J0IE1JTklPX0JST1dTRVI9Im9uIgo=
kind: Secret
metadata:
  labels:
    v1.min.io/tenant: minio
  name: minio-env-configuration
  namespace: minio
type: Opaque
