apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  labels:
    cluster.open-cluster-management.io/backup: resource
  name: cluster1-cluster2-1m
spec:
  drClusters:
    - cluster2
    - local-cluster
  replicationClassSelector: {}
  schedulingInterval: 1m
  volumeSnapshotClassSelector: {}
