apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc
  namespace: openshift-gitops
  labels:
    cluster.open-cluster-management.io/backup: resource
spec:
  preferredCluster: local-cluster
  action: "Relocate"
  drPolicyRef:
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: DRPolicy
    name: cluster1-cluster2-1m
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: busybox
    namespace: openshift-gitops
  pvcSelector:
    matchLabels:
      appname: busybox
