---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: pvc
spec:
  # The PVC to sync
  sourcePVC: pvc-block-rwo
  trigger:
    schedule: "* * * * *"
#    manual: manual1
  rclone:
    # The configuration section of the rclone config file to use
    rcloneConfigSection: "aws-s3-bucket"
    # The path to the object bucket
    rcloneDestPath: "bucket/pvc"
    # Secret holding the rclone configuration
    rcloneConfig: "rclone-secret"
    # Method used to generate the PiT copy
    copyMethod: Snapshot
    # The StorageClass to use when creating the PiT copy (same as source PVC if omitted)
    storageClassName: managed-csi
    # The VSC to use if the copy method is Snapshot (default if omitted)
    volumeSnapshotClassName: csi-azuredisk-vsc
